title: Its Just Joe Games
author:
  name: Joe
  email: info@itsjustjoe.games

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Passionate about creating indie games and sharing my game development journey. 
  Here, you’ll find a blend of gaming and tech content as I dive into the challenges 
  and triumphs of bringing my game ideas to life.
  
# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
#remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md
  - games.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: false

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  skin: dark
  
  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  date_format: "%b-%d-%Y"

  # Generate social links in footer.
  social_links:
    - { platform: youtube,        user_url: "https://www.youtube.com/@ItsJustJoeGames?=sub1" }
    - platform: steam  # same as SVG filename.
      user_url: "https://store.steampowered.com/app/2233640/Bunker_Breakout/"  # URL of profile page.
      title:  My games on steam  # Optional. Text displayed on hovering over link.
  #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    - { platform: bluesky,         user_url: "https://bsky.app/profile/itsjustjoe.games" }
  #  - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  #  - { platform: gitlab,         user_url: "https://gitlab.com/jekyll" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: blusky,        user_url: "https://bsky.app/profile/itsjustjoe.games }
    - { platform: x,              user_url: "https://x.com/Its_Just_Joe_" }
